```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(viridis)
library(Hmisc)
library(reshape2) 
library(reshape) 
library(tidyverse)
```

# Theme, guides, facet funtion

```{r}
standard_theme <- ggplot2::theme(panel.background = element_rect(fill='white', colour='black')) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(legend.key = element_rect(color = "transparent"))  + 
  theme(panel.spacing=unit(0,"lines"),
        strip.background=element_rect(color="grey30", fill="grey90"),
        axis.text.x = element_text(angle = 60, vjust = 0.2, hjust=0.2))
  
standard_guides <-guides(fill="none",color=guide_legend(override.aes=list(fill=NA))) 

standard_facet <- facet_grid(size~death_chance) 
        
standard_visuals <- list(standard_theme, standard_guides, standard_facet)
```

# Read data

```{r}
folder <- ""
```

```{r}
counts_df <- read.csv(paste0(folder,"org_counts.dat"),h=T)
counts_df$seed <- as.factor(counts_df$seed)

if("treatment" %in% colnames(counts_df)){
  counts_df$treatment <- ifelse(counts_df$treatment == 0, "Mutualist", counts_df$treatment)
  counts_df$treatment <- ifelse(counts_df$treatment == 1, "Parasite", counts_df$treatment)
  counts_df$treatment <- ifelse(counts_df$treatment == 2, "Neutral", counts_df$treatment)
}
```

```{r}
tasks_df <- read.csv(paste0(folder,"task_counts.dat"),h=T)
tasks_df$seed <- as.factor(tasks_df$seed)

if("treatment" %in% colnames(tasks_df)){
  counts_df$treatment <- ifelse(counts_df$treatment == 0, "Mutualist", counts_df$treatment)
  counts_df$treatment <- ifelse(counts_df$treatment == 1, "Parasite", counts_df$treatment)
  counts_df$treatment <- ifelse(counts_df$treatment == 2, "Neutral", counts_df$treatment)
}
```

# Organism counts

```{r}
ggplot(subset(counts_df, update %% 5000 == 0),aes(x=update)) + 
  stat_summary(aes(y=count,fill="Hosts",color="Hosts"),
               fun.data="mean_cl_boot", geom=c("smooth"), se=TRUE) +
  stat_summary(aes(y=hosted_syms,fill="Symbionts",color="Syms"),
               fun.data="mean_cl_boot", geom=c("smooth"), se=TRUE) +
  ylab("Organism count") + xlab("Update") +
  scale_colour_manual(name="Organism", values=plasma(3)) + 
  scale_fill_manual(values=plasma(3)) + 
  standard_visuals
 
```

# Task Counts

```{r}
task_plotter <- function(data_frame, weigh_by, ylab, exl_not=F){
  colors <- turbo(10)
  if(exl_not){
    colors <- colors[2:10]
    data_frame <- subset(data_frame, variable != "host_task_NOT" & variable != "sym_task_NOT")
  }
  plot <- ggplot(data_frame,aes(x=update))  
  plot <- plot + stat_summary(aes(y=value/weigh_by, color=variable, fill=variable),
                                fun.data="mean_cl_boot", geom=c("smooth"), se=TRUE) 
  
  plot + ylab(ylab) + xlab("Update") +
    standard_visuals +  
    scale_colour_manual(name="Task type", values=colors) + 
    scale_fill_manual(values=colors) + 
    theme(axis.text.x = element_text(angle = 60, vjust = 0.2, hjust=0.2)) 
}


not_plotter <- function(data_frame, weigh_by, ylab){
  colors <- turbo(10)
  colors <- colors[1]
  data_frame <- subset(data_frame, variable == "host_task_NOT" | variable == "sym_task_NOT")
  
  plot <- ggplot(data_frame,aes(x=update))  
  plot <- plot + stat_summary(aes(y=value/weigh_by, color=variable, fill=variable),
                                fun.data="mean_cl_boot", geom=c("smooth"), se=TRUE) 
  
  plot + ylab(ylab) + xlab("Update") +
    standard_visuals +  
    scale_colour_manual(name="Task type", values=colors) + 
    scale_fill_manual(values=colors) + 
    theme(axis.text.x = element_text(angle = 60, vjust = 0.2, hjust=0.2)) 
}
```

```{r}
molten_tasks <- melt(tasks_df, id=c("seed","death_chance","size", "update"))

molten_tasks$host_task <- grepl("host",molten_tasks$variable, fixed=TRUE)
molten_tasks <- subset(molten_tasks, update %% 5000 == 0)
small_counts <- subset(counts_df, update %% 5000 == 0)
```

```{r}
task_plotter(subset(molten_tasks, host_task), 1, "Host task count")
task_plotter(subset(molten_tasks, host_task), small_counts$count, "Host task count / Host count")
```
